// flow-typed signature: 26c44fc8b3dc79fc09ae013c1abf2e05
// flow-typed version: <<STUB>>/immutable_v4.0.0-rc.12/flow_v0.105.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'immutable'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'immutable' {
  declare module.exports: any;
}
